site_name: IT alased õppematerjalid 
theme:
  name: material
  custom_dir: overrides
  language: et
  favicon: images/computer.png
  icon:
    logo: fontawesome/solid/computer
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate

  plugins:
    - typeset
    - search

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Lülitu heledale režiimile

    # Palette toggle for light mode
    - scheme: default
      primary: deep blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Lülitu tumedale režiimile

#markdown_extensions:
#   - toc:
#      permalink: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


copyright: Copyright &copy; 2024 Priit Paap

nav:
  - Avalehele: http://127.0.0.1:8000/
  - Õppematerjalid:
    - 'Sissejuhatuseks':
      - 'Sissejuhatuseks': intro.md
    - 'Windows':
      - 'Windowsi paigaldamine virutaalmasinale': leht1.md
      - 'Windows Serveri paigaldamine virutaalmasinale': leht2.md 
    - 'Linux':
      - 'Linuxi paigaldamine virutaalmasinale': leht3.md
      - 'Linux serveri paigaldamine virutaalmasinale': leht4.md 
  - Mingi tore link: https://priiduveeb.eu
