site_name: IT alased õppematerjalid 
theme:
  name: material
  custom_dir: overrides
  language: et
  favicon: images/computer.png
  icon:
    logo: fontawesome/solid/computer
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
#    - toc.integrate

  plugins:
    - typeset
    - search

  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Lülitu heledale režiimile

    # Palette toggle for light mode
    - scheme: default
      primary: deep blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Lülitu tumedale režiimile

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


copyright: Copyright &copy; 2025 Priit Paap

nav:
  - Avalehele: https://itasjad.priiduveeb.eu
  - Operatsioonisüsteemid:
  #  - 'Windows OS':
  #    - 'Windowsi paigaldamine virutaalmasinale': leht1.md
  #    - 'Windows Serveri paigaldamine virutaalmasinale': leht2.md 
    - 'Linux OS':
      - 'Debian Linuxi paigaldamine virutaalmasinale': debpaigaldus.md 
 # - Mingi tore link: https://priiduveeb.eu
  - Automatiseerimine:
    - 'Ansible':
      - 'Ansible ülevaade': ansibleintro.md
      - 'Ansible paigaldamine': ansibleinstall.md
      - 'Inventory ja hostide haldus': ansibleinventory.md
      - 'Hallatavate hostide ühendamine': ansiblenodes.md
      - 'Moodulid ja ad-hoc käsud': ansiblemodules.md
      - 'Playbookid ja YAML': ansibleplaybooks.md
      - 'Muutujad ja Jinja2 mallid': ansiblevars.md
      - 'Tingimuslikkus ja tsüklid': ansibleconditions.md
      - 'Rollid ja struktuur': ansibleroles.md
      - 'Ansible Galaxy ja kogukonna rollid': ansiblerolesgalaxy.md
      - 'Ansible konfiguratsioon ja optimeerimine': ansibleconf.md
      - 'Turvalisus ja Ansible Vault': ansiblevault.md
      - 'Projektipõhine lõppharjutus': ansiblefinal.md
      - 'Ansible parimad praktikad': ansiblebestpractises.md







  